#!/usr/bin/env python3
"""Generate the 4 fine-tuning notebooks from a shared template.

Each notebook is identical except for the configuration cell (cell 0).
Run this script from the notebooks/examples/ directory:

    python _build_notebooks.py

It will create / overwrite:
    finetune_st_random.ipynb
    finetune_st_pretrained.ipynb
    finetune_mt_random.ipynb
    finetune_mt_pretrained.ipynb
"""

import json
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration variants
# ---------------------------------------------------------------------------
VARIANTS = [
    {
        "filename": "finetune_st_random.ipynb",
        "config_source": [
            "# === CONFIGURATION (ONLY SECTION THAT DIFFERS ACROSS NOTEBOOKS) ===\n",
            'NUM_TASKS = 1                          # 1 = single-task (LogD only)\n',
            'PRETRAINED_CHECKPOINT = None            # None = random init\n',
            'EXPERIMENT_NAME = "st_random"\n',
        ],
    },
    {
        "filename": "finetune_st_pretrained.ipynb",
        "config_source": [
            "# === CONFIGURATION (ONLY SECTION THAT DIFFERS ACROSS NOTEBOOKS) ===\n",
            'NUM_TASKS = 1                          # 1 = single-task (LogD only)\n',
            'PRETRAINED_CHECKPOINT = "../../experiments/pretrain/best_checkpoint.pt"\n',
            'EXPERIMENT_NAME = "st_pretrained"\n',
        ],
    },
    {
        "filename": "finetune_mt_random.ipynb",
        "config_source": [
            "# === CONFIGURATION (ONLY SECTION THAT DIFFERS ACROSS NOTEBOOKS) ===\n",
            'NUM_TASKS = 9                          # 9 = multi-task (all endpoints)\n',
            'PRETRAINED_CHECKPOINT = None            # None = random init\n',
            'EXPERIMENT_NAME = "mt_random"\n',
        ],
    },
    {
        "filename": "finetune_mt_pretrained.ipynb",
        "config_source": [
            "# === CONFIGURATION (ONLY SECTION THAT DIFFERS ACROSS NOTEBOOKS) ===\n",
            'NUM_TASKS = 9                          # 9 = multi-task (all endpoints)\n',
            'PRETRAINED_CHECKPOINT = "../../experiments/pretrain/best_checkpoint.pt"\n',
            'EXPERIMENT_NAME = "mt_pretrained"\n',
        ],
    },
]

# ---------------------------------------------------------------------------
# Shared cells (byte-identical across all 4 notebooks)
# ---------------------------------------------------------------------------
SHARED_CELLS = [
    # --- CELL: Imports + constants ---
    {
        "cell_type": "code",
        "source": [
            "# === IMPORTS + CONSTANTS (identical across all notebooks) ===\n",
            "\n",
            "import os\n",
            "import math\n",
            "import copy\n",
            "import random\n",
            "import warnings\n",
            "from pathlib import Path\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import torch\n",
            "import torch.nn.functional as F\n",
            "from torch_geometric.loader import DataLoader\n",
            "from sklearn.metrics import r2_score\n",
            "from scipy.stats import spearmanr, kendalltau\n",
            "\n",
            "from gt_pyg import GraphTransformerNet, get_tensor_data\n",
            "from gt_pyg.data import get_atom_feature_dim, get_bond_feature_dim\n",
            "\n",
            "warnings.filterwarnings('ignore', category=FutureWarning)\n",
            "\n",
            "# --- Reproducibility ---\n",
            "SEED = 1928374650\n",
            "\n",
            "def seed_everything(seed: int = SEED):\n",
            "    random.seed(seed)\n",
            "    np.random.seed(seed)\n",
            "    torch.manual_seed(seed)\n",
            "    if torch.cuda.is_available():\n",
            "        torch.cuda.manual_seed_all(seed)\n",
            "    os.environ['PYTHONHASHSEED'] = str(seed)\n",
            "    torch.backends.cudnn.deterministic = True\n",
            "    torch.backends.cudnn.benchmark = False\n",
            "\n",
            "seed_everything()\n",
            "\n",
            "# --- Hyperparameters ---\n",
            "BATCH_TRAIN = 256\n",
            "BATCH_EVAL = 1024\n",
            "EPOCHS = 2000                # production (set to 10 for quick test)\n",
            "BASE_LR = 1e-3\n",
            "MIN_LR = 1e-5                # BASE_LR / 100\n",
            "WEIGHT_DECAY = 1e-5\n",
            "WARMUP_EPOCHS = 25\n",
            "GRAD_CLIP_NORM = 5.0\n",
            "DELTA = 0.2                  # clipping margin beyond train range\n",
            "T_MAX = min(500, EPOCHS)\n",
            "NUM_WORKERS = 4\n",
            "\n",
            "# Loss weights\n",
            "W_RAE = 1.0\n",
            "W_HUBER = 0.25\n",
            "W_CORR = 0.25\n",
            "W_TAU = 0.1\n",
            "W_R2 = 0.1\n",
            "HUBER_DELTA = 0.5\n",
            "TAU_TEMP = 2.0\n",
            "RANK_PAIRS = 512\n",
            "\n",
            "SPLIT_FRACTIONS = [0.7, 0.2, 0.1]\n",
            "\n",
            "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "print(f'Device: {device}')\n",
            "print(f'NUM_TASKS: {NUM_TASKS}')\n",
            "print(f'PRETRAINED_CHECKPOINT: {PRETRAINED_CHECKPOINT}')\n",
            "print(f'EXPERIMENT_NAME: {EXPERIMENT_NAME}')\n",
        ],
    },
    # --- CELL: Data loading ---
    {
        "cell_type": "code",
        "source": [
            "# === DATA LOADING ===\n",
            "\n",
            "TRAIN_CSV = '../../data/train-set/expansion_log_data_train.csv'\n",
            "TEST_CSV = '../../data/test-set/expansion_data_test_full_lb_flag.csv'\n",
            "\n",
            "log_train_df = pd.read_csv(TRAIN_CSV)\n",
            "test_df = pd.read_csv(TEST_CSV)\n",
            "\n",
            "# All 9 log-scale endpoints\n",
            "ALL_LOG_ENDPOINTS = [\n",
            "    'LogD', 'LogS', 'Log_HLM_CLint', 'Log_MLM_CLint',\n",
            "    'Log_Caco_Papp_AB', 'Log_Caco_ER',\n",
            "    'Log_Mouse_PPB', 'Log_Mouse_BPB', 'Log_Mouse_MPB',\n",
            "]\n",
            "\n",
            "# Select endpoints based on NUM_TASKS\n",
            "if NUM_TASKS == 1:\n",
            "    ENDPOINTS = ['LogD']\n",
            "else:\n",
            "    ENDPOINTS = ALL_LOG_ENDPOINTS\n",
            "    assert NUM_TASKS == len(ENDPOINTS)\n",
            "\n",
            "print(f'Training data: {len(log_train_df)} molecules, {len(ENDPOINTS)} endpoints')\n",
            "print(f'Test data: {len(test_df)} molecules')\n",
            "print(f'Endpoints: {ENDPOINTS}')\n",
        ],
    },
    # --- CELL: Log transforms ---
    {
        "cell_type": "code",
        "source": [
            "# === LOG TRANSFORMS ===\n",
            "# v1 transforms matching the pre-computed training CSV.\n",
            "# Forward:  log10((val + 1) * multiplier)\n",
            "# Inverse:  (10^val / multiplier) - 1, clipped >= 0\n",
            "\n",
            "ENDPOINT_MAP = {\n",
            "    # original_col: (log_col, multiplier)\n",
            "    'LogD':                          ('LogD', 1),\n",
            "    'KSOL':                          ('LogS', 1e-6),\n",
            "    'HLM CLint':                     ('Log_HLM_CLint', 1),\n",
            "    'MLM CLint':                     ('Log_MLM_CLint', 1),\n",
            "    'Caco-2 Permeability Papp A>B':  ('Log_Caco_Papp_AB', 1e-6),\n",
            "    'Caco-2 Permeability Efflux':    ('Log_Caco_ER', 1),\n",
            "    'MPPB':                          ('Log_Mouse_PPB', 1),\n",
            "    'MBPB':                          ('Log_Mouse_BPB', 1),\n",
            "    'MGMB':                          ('Log_Mouse_MPB', 1),\n",
            "}\n",
            "\n",
            "# Build reverse map: log_col -> (original_col, multiplier)\n",
            "REVERSE_MAP = {v[0]: (k, v[1]) for k, v in ENDPOINT_MAP.items()}\n",
            "\n",
            "\n",
            "def log_transform_test_data(test_df, endpoints):\n",
            "    \"\"\"Transform test data from original scale to log scale.\"\"\"\n",
            "    result = pd.DataFrame()\n",
            "    result['SMILES'] = test_df['SMILES']\n",
            "    result['Molecule Name'] = test_df['Molecule Name']\n",
            "    for log_col in endpoints:\n",
            "        orig_col, mult = REVERSE_MAP[log_col]\n",
            "        if orig_col in test_df.columns:\n",
            "            vals = test_df[orig_col].values.astype(float)\n",
            "            if log_col == 'LogD':  # already log-scale\n",
            "                result[log_col] = vals\n",
            "            else:\n",
            "                result[log_col] = np.log10((vals + 1) * mult)\n",
            "        else:\n",
            "            result[log_col] = np.nan\n",
            "    if 'is_leaderboard' in test_df.columns:\n",
            "        result['is_leaderboard'] = test_df['is_leaderboard'].values\n",
            "    return result\n",
            "\n",
            "\n",
            "def inverse_log_transform(preds_df, endpoints):\n",
            "    \"\"\"Transform predictions from log scale back to original scale.\"\"\"\n",
            "    result = preds_df.copy()\n",
            "    for log_col in endpoints:\n",
            "        orig_col, mult = REVERSE_MAP[log_col]\n",
            "        if log_col in result.columns:\n",
            "            vals = result[log_col].values.astype(float)\n",
            "            if log_col == 'LogD':  # already original-ish scale\n",
            "                pass  # no transform needed\n",
            "            else:\n",
            "                result[log_col] = np.maximum((10 ** vals / mult) - 1, 0)\n",
            "    return result\n",
            "\n",
            "\n",
            "# Transform test data to log scale for training/evaluation\n",
            "log_test_df = log_transform_test_data(test_df, ENDPOINTS)\n",
            "print(f'Log-transformed test data: {len(log_test_df)} rows')\n",
        ],
    },
    # --- CELL: Data splitting + PyG datasets ---
    {
        "cell_type": "code",
        "source": [
            "# === DATA SPLITTING + PyG DATASETS ===\n",
            "\n",
            "def split_data(n, fractions, seed=SEED):\n",
            "    \"\"\"Random split into subsets. Returns index arrays.\"\"\"\n",
            "    rng = np.random.RandomState(seed)\n",
            "    indices = rng.permutation(n)\n",
            "    splits = []\n",
            "    start = 0\n",
            "    for i, frac in enumerate(fractions):\n",
            "        if i == len(fractions) - 1:\n",
            "            splits.append(indices[start:])\n",
            "        else:\n",
            "            end = start + int(n * frac)\n",
            "            splits.append(indices[start:end])\n",
            "            start = end\n",
            "    return tuple(splits)\n",
            "\n",
            "\n",
            "# Split train CSV into train/val/test\n",
            "n = len(log_train_df)\n",
            "train_idx, val_idx, test_from_train_idx = split_data(n, SPLIT_FRACTIONS)\n",
            "\n",
            "train_df = log_train_df.iloc[train_idx].reset_index(drop=True)\n",
            "val_df = log_train_df.iloc[val_idx].reset_index(drop=True)\n",
            "test_from_train_df = log_train_df.iloc[test_from_train_idx].reset_index(drop=True)\n",
            "\n",
            "print(f'Split: train={len(train_df)}  val={len(val_df)}  test_from_train={len(test_from_train_df)}')\n",
            "\n",
            "# Build PyG datasets\n",
            "def build_dataset(df, endpoints):\n",
            "    smiles = df['SMILES'].astype(str).tolist()\n",
            "    Y = df[list(endpoints)].to_numpy(dtype=float).tolist()\n",
            "    return get_tensor_data(smiles, Y, gnm=True)\n",
            "\n",
            "\n",
            "print('Building datasets...')\n",
            "train_data = build_dataset(train_df, ENDPOINTS)\n",
            "val_data = build_dataset(val_df, ENDPOINTS)\n",
            "test_from_train_data = build_dataset(test_from_train_df, ENDPOINTS)\n",
            "\n",
            "# Also build external test set (log-transformed)\n",
            "ext_test_data = build_dataset(log_test_df, ENDPOINTS)\n",
            "\n",
            "train_loader = DataLoader(train_data, batch_size=BATCH_TRAIN, shuffle=True, num_workers=NUM_WORKERS, persistent_workers=NUM_WORKERS > 0)\n",
            "val_loader = DataLoader(val_data, batch_size=BATCH_EVAL, shuffle=False, num_workers=NUM_WORKERS, persistent_workers=NUM_WORKERS > 0)\n",
            "test_from_train_loader = DataLoader(test_from_train_data, batch_size=BATCH_EVAL, shuffle=False)\n",
            "ext_test_loader = DataLoader(ext_test_data, batch_size=BATCH_EVAL, shuffle=False)\n",
            "\n",
            "print('Datasets built.')\n",
        ],
    },
    # --- CELL: Model construction ---
    {
        "cell_type": "code",
        "source": [
            "# === MODEL CONSTRUCTION ===\n",
            "\n",
            "model = GraphTransformerNet(\n",
            "    node_dim_in=get_atom_feature_dim(),\n",
            "    edge_dim_in=get_bond_feature_dim(),\n",
            "    num_gt_layers=4,\n",
            "    hidden_dim=128,\n",
            "    num_heads=8,\n",
            "    norm='bn',\n",
            "    gt_aggregators=['sum', 'mean'],\n",
            "    aggregators=['sum', 'mean', 'max', 'std'],\n",
            "    dropout=0.3,\n",
            "    act='gelu',\n",
            "    gate=True,\n",
            "    qkv_bias=False,\n",
            "    num_tasks=NUM_TASKS,\n",
            ").to(device)\n",
            "\n",
            "n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
            "print(f'Model: {n_params:,} trainable parameters, num_tasks={NUM_TASKS}')\n",
        ],
    },
    # --- CELL: Pretrained weight loading ---
    {
        "cell_type": "code",
        "source": [
            "# === PRETRAINED WEIGHT LOADING (shape-filter pattern) ===\n",
            "# BUG FIX: PyTorch strict=False does NOT handle shape mismatches —\n",
            "# it only handles missing/extra keys. We must filter by shape.\n",
            "\n",
            "if PRETRAINED_CHECKPOINT is not None:\n",
            "    ckpt_path = Path(PRETRAINED_CHECKPOINT)\n",
            "    if not ckpt_path.exists():\n",
            "        print(f'WARNING: Checkpoint not found at {ckpt_path} — using random init')\n",
            "    else:\n",
            "        checkpoint = torch.load(ckpt_path, map_location=device, weights_only=False)\n",
            "        pretrain_sd = checkpoint['model_state_dict']\n",
            "        finetune_sd = model.state_dict()\n",
            "\n",
            "        compatible_sd = {\n",
            "            k: v for k, v in pretrain_sd.items()\n",
            "            if k in finetune_sd and v.shape == finetune_sd[k].shape\n",
            "        }\n",
            "        skipped = [\n",
            "            k for k in pretrain_sd\n",
            "            if k not in finetune_sd or pretrain_sd[k].shape != finetune_sd.get(k, torch.tensor([])).shape\n",
            "        ]\n",
            "\n",
            "        model.load_state_dict(compatible_sd, strict=False)\n",
            "        print(f'Loaded {len(compatible_sd)}/{len(pretrain_sd)} pretrained keys')\n",
            "        if skipped:\n",
            "            print(f'Skipped (shape mismatch or missing): {skipped}')\n",
            "else:\n",
            "    print('Random initialization (no pretrained checkpoint)')\n",
        ],
    },
    # --- CELL: Loss functions ---
    {
        "cell_type": "code",
        "source": [
            "# === 5-COMPONENT CUSTOM LOSS ===\n",
            "\n",
            "\n",
            "@torch.no_grad()\n",
            "def compute_task_scales(loader, num_tasks, eps=1e-8):\n",
            "    \"\"\"MAD per task from training data, for RAE normalization.\"\"\"\n",
            "    ys = [[] for _ in range(num_tasks)]\n",
            "    for batch in loader:\n",
            "        y = batch.y.view(-1, num_tasks).cpu().numpy()\n",
            "        m = batch.y_mask.view(-1, num_tasks).cpu().numpy().astype(bool)\n",
            "        for t in range(num_tasks):\n",
            "            yt = y[m[:, t], t]\n",
            "            yt = yt[np.isfinite(yt)]\n",
            "            if yt.size:\n",
            "                ys[t].append(yt)\n",
            "    scales = []\n",
            "    for t in range(num_tasks):\n",
            "        if not ys[t]:\n",
            "            scales.append(1.0)\n",
            "            continue\n",
            "        v = np.concatenate(ys[t])\n",
            "        if v.size < 3:\n",
            "            scales.append(1.0)\n",
            "            continue\n",
            "        med = np.median(v)\n",
            "        mad = np.median(np.abs(v - med))\n",
            "        scales.append(float(max(mad, eps)))\n",
            "    return torch.tensor(scales, dtype=torch.float32)\n",
            "\n",
            "\n",
            "def masked_weighted_rae_loss(pred, y, mask, task_scale, eps=1e-8, clip_val=100.0):\n",
            "    \"\"\"Relative absolute error normalized by per-task MAD.\"\"\"\n",
            "    pred = torch.clamp(pred, -clip_val, clip_val)\n",
            "    valid = (mask > 0) & torch.isfinite(y) & torch.isfinite(pred)\n",
            "    diff = torch.where(valid, (pred - y).abs() / (task_scale.to(pred.device) + eps), torch.zeros_like(pred))\n",
            "    w = torch.where(valid, torch.ones_like(pred), torch.zeros_like(pred))\n",
            "    sum_t = (diff * w).sum(dim=0)\n",
            "    sum_w = w.sum(dim=0).clamp_min(eps)\n",
            "    mean_t = sum_t / sum_w\n",
            "    task_mask = w.sum(dim=0) > 0\n",
            "    return mean_t[task_mask].mean() if task_mask.any() else pred.new_tensor(0.0)\n",
            "\n",
            "\n",
            "def masked_weighted_huber_loss(pred, y, mask, delta=1.0, task_scale=None, clip_val=100.0, eps=1e-8):\n",
            "    \"\"\"Huber loss, optionally normalized by task scale.\"\"\"\n",
            "    pred = torch.clamp(pred, -clip_val, clip_val)\n",
            "    valid = (mask > 0) & torch.isfinite(y) & torch.isfinite(pred)\n",
            "    diff = torch.where(valid, pred - y, torch.zeros_like(pred))\n",
            "    if task_scale is not None:\n",
            "        diff = diff / (task_scale.to(diff.device) + eps)\n",
            "    abs_diff = diff.abs()\n",
            "    quad = torch.minimum(abs_diff, abs_diff.new_tensor(delta))\n",
            "    loss = 0.5 * quad ** 2 + delta * (abs_diff - quad)\n",
            "    w = torch.where(valid, torch.ones_like(pred), torch.zeros_like(pred))\n",
            "    sum_t = (loss * w).sum(dim=0)\n",
            "    sum_w = w.sum(dim=0).clamp_min(eps)\n",
            "    mean_t = sum_t / sum_w\n",
            "    task_mask = w.sum(dim=0) > 0\n",
            "    return mean_t[task_mask].mean() if task_mask.any() else pred.new_tensor(0.0)\n",
            "\n",
            "\n",
            "def masked_weighted_corr_loss(pred, y, mask, eps=1e-8, clip_val=100.0):\n",
            "    \"\"\"1 - Pearson correlation per task.\"\"\"\n",
            "    pred = torch.clamp(pred, -clip_val, clip_val)\n",
            "    valid = (mask > 0) & torch.isfinite(y) & torch.isfinite(pred)\n",
            "    w = torch.where(valid, torch.ones_like(pred), torch.zeros_like(pred))\n",
            "    sum_w = w.sum(dim=0).clamp_min(eps)\n",
            "    p_v = torch.where(valid, pred, torch.zeros_like(pred))\n",
            "    y_v = torch.where(valid, y, torch.zeros_like(y))\n",
            "    mean_p = (w * p_v).sum(dim=0) / sum_w\n",
            "    mean_y = (w * y_v).sum(dim=0) / sum_w\n",
            "    p_c = torch.where(valid, p_v - mean_p.unsqueeze(0), torch.zeros_like(pred))\n",
            "    y_c = torch.where(valid, y_v - mean_y.unsqueeze(0), torch.zeros_like(y))\n",
            "    cov = (w * p_c * y_c).sum(dim=0)\n",
            "    std_p = torch.sqrt((w * p_c ** 2).sum(dim=0) + eps)\n",
            "    std_y = torch.sqrt((w * y_c ** 2).sum(dim=0) + eps)\n",
            "    corr = cov / (std_p * std_y + eps)\n",
            "    per_task = 1.0 - corr\n",
            "    task_mask = w.sum(dim=0) > 0\n",
            "    return per_task[task_mask].mean() if task_mask.any() else pred.new_tensor(0.0)\n",
            "\n",
            "\n",
            "def masked_weighted_kendall_rank_loss(pred, y, mask, num_pairs=512, tau_temp=1.0, clip_val=100.0, eps=1e-8):\n",
            "    \"\"\"Differentiable Kendall rank loss via sampled pairs.\"\"\"\n",
            "    pred = torch.clamp(pred, -clip_val, clip_val)\n",
            "    B, T = pred.shape\n",
            "    mask_b = mask.bool()\n",
            "    per_task_loss = []\n",
            "    for t in range(T):\n",
            "        valid_t = mask_b[:, t] & torch.isfinite(y[:, t]) & torch.isfinite(pred[:, t])\n",
            "        idx = torch.where(valid_t)[0]\n",
            "        n = idx.numel()\n",
            "        if n < 2:\n",
            "            per_task_loss.append(pred.new_tensor(0.0))\n",
            "            continue\n",
            "        max_pairs = n * (n - 1) // 2\n",
            "        ii, jj = torch.triu_indices(n, n, offset=1, device=pred.device)\n",
            "        if max_pairs > num_pairs:\n",
            "            probe = min(max_pairs, 8192)\n",
            "            choose = torch.randperm(max_pairs, device=pred.device)[:probe]\n",
            "            ia, ib = ii[choose], jj[choose]\n",
            "            ydiff = (y[idx[ia], t] - y[idx[ib], t]).abs()\n",
            "            topk = torch.topk(ydiff, k=min(num_pairs, probe)).indices\n",
            "            ia, ib = ia[topk], ib[topk]\n",
            "        else:\n",
            "            ia, ib = ii, jj\n",
            "        a, b = idx[ia], idx[ib]\n",
            "        s = torch.sign(y[a, t] - y[b, t])\n",
            "        p_diff = pred[a, t] - pred[b, t]\n",
            "        non_tie = s != 0\n",
            "        if non_tie.any():\n",
            "            per_task_loss.append(F.softplus(-s[non_tie] * p_diff[non_tie] / tau_temp).mean())\n",
            "        else:\n",
            "            per_task_loss.append(pred.new_tensor(0.0))\n",
            "    losses = torch.stack(per_task_loss)\n",
            "    return losses.mean()\n",
            "\n",
            "\n",
            "def masked_r2_style_loss(pred, y, mask, eps=1e-8, clip_val=100.0):\n",
            "    \"\"\"R2-style loss: SSE / Var(y) per task.\"\"\"\n",
            "    pred = torch.clamp(pred, -clip_val, clip_val)\n",
            "    valid = mask.bool() & torch.isfinite(y) & torch.isfinite(pred)\n",
            "    counts = valid.sum(dim=0)\n",
            "    has_data = counts > 1\n",
            "    if not has_data.any():\n",
            "        return pred.new_tensor(0.0)\n",
            "    p_v = torch.where(valid, pred, torch.zeros_like(pred))\n",
            "    y_v = torch.where(valid, y, torch.zeros_like(y))\n",
            "    mean_y = y_v.sum(dim=0) / (counts + eps)\n",
            "    y_c = torch.where(valid, y - mean_y.unsqueeze(0), torch.zeros_like(y))\n",
            "    sse = ((p_v - y_v) ** 2).sum(dim=0)\n",
            "    var_y = (y_c ** 2).sum(dim=0)\n",
            "    good = has_data & (var_y > eps)\n",
            "    if not good.any():\n",
            "        return pred.new_tensor(0.0)\n",
            "    return (sse[good] / (var_y[good] + eps)).mean()\n",
            "\n",
            "\n",
            "def custom_loss(pred, y, mask, *, task_scale):\n",
            "    \"\"\"Combined 5-component loss.\"\"\"\n",
            "    L = pred.new_tensor(0.0)\n",
            "    if W_RAE > 0:\n",
            "        L = L + W_RAE * masked_weighted_rae_loss(pred, y, mask, task_scale)\n",
            "    if W_HUBER > 0:\n",
            "        L = L + W_HUBER * masked_weighted_huber_loss(pred, y, mask, delta=HUBER_DELTA, task_scale=task_scale)\n",
            "    if W_CORR > 0:\n",
            "        L = L + W_CORR * masked_weighted_corr_loss(pred, y, mask)\n",
            "    if W_TAU > 0:\n",
            "        L = L + W_TAU * masked_weighted_kendall_rank_loss(pred, y, mask, num_pairs=RANK_PAIRS, tau_temp=TAU_TEMP)\n",
            "    if W_R2 > 0:\n",
            "        L = L + W_R2 * masked_r2_style_loss(pred, y, mask)\n",
            "    return L\n",
            "\n",
            "\n",
            "# Compute task scales from training data\n",
            "task_scale = compute_task_scales(train_loader, NUM_TASKS).to(device)\n",
            "print(f'Task scales (MAD): {task_scale.cpu().tolist()}')\n",
        ],
    },
    # --- CELL: Metrics ---
    {
        "cell_type": "code",
        "source": [
            "# === METRICS ===\n",
            "\n",
            "def official_metrics(y_true, y_pred):\n",
            "    \"\"\"Compute MAE, RAE, R2, Spearman, Kendall for 1D arrays.\"\"\"\n",
            "    y = np.asarray(y_true).ravel()\n",
            "    p = np.asarray(y_pred).ravel()\n",
            "    m = np.isfinite(y) & np.isfinite(p)\n",
            "    y, p = y[m], p[m]\n",
            "    if y.size == 0:\n",
            "        return {'MAE': np.nan, 'RAE': np.nan, 'R2': np.nan, 'Spearman': np.nan, 'Kendall': np.nan}\n",
            "    mae = float(np.mean(np.abs(y - p)))\n",
            "    denom = np.mean(np.abs(y - np.mean(y)))\n",
            "    rae = float(mae / denom) if denom > 0 else np.nan\n",
            "    r2 = float(r2_score(y, p)) if np.std(y) > 0 else np.nan\n",
            "    spr = float(spearmanr(y, p).statistic) if np.std(p) > 1e-6 else np.nan\n",
            "    ktau = float(kendalltau(y, p).statistic) if np.std(p) > 1e-6 else np.nan\n",
            "    return {'MAE': mae, 'RAE': rae, 'R2': r2, 'Spearman': spr, 'Kendall': ktau}\n",
            "\n",
            "\n",
            "@torch.no_grad()\n",
            "def evaluate_loader(model, loader, endpoints):\n",
            "    \"\"\"Evaluate model on a loader. Returns (macro_rae, per_endpoint_metrics, preds, targets, masks).\"\"\"\n",
            "    model.eval()\n",
            "    preds_all, y_all, m_all = [], [], []\n",
            "    T = len(endpoints)\n",
            "    for batch in loader:\n",
            "        batch = batch.to(device)\n",
            "        out, _ = model(batch.x, batch.edge_index, batch.edge_attr, batch=batch.batch, zero_var=False)\n",
            "        y = batch.y.view(-1, T)\n",
            "        mask = batch.y_mask.view(-1, T)\n",
            "        preds_all.append(out.cpu().numpy())\n",
            "        y_all.append(y.cpu().numpy())\n",
            "        m_all.append(mask.cpu().numpy())\n",
            "    if not preds_all:\n",
            "        return np.inf, {}, np.zeros((0, T)), np.zeros((0, T)), np.zeros((0, T))\n",
            "    preds = np.vstack(preds_all)\n",
            "    ys = np.vstack(y_all)\n",
            "    masks = np.vstack(m_all)\n",
            "    metrics = {}\n",
            "    raes = []\n",
            "    for i, ep in enumerate(endpoints):\n",
            "        m = masks[:, i].astype(bool) & np.isfinite(ys[:, i])\n",
            "        if m.sum() < 3:\n",
            "            metrics[ep] = {'MAE': np.nan, 'RAE': np.nan, 'R2': np.nan, 'Spearman': np.nan, 'Kendall': np.nan}\n",
            "            continue\n",
            "        metrics[ep] = official_metrics(ys[m, i], preds[m, i])\n",
            "        raes.append(metrics[ep]['RAE'])\n",
            "    macro_rae = float(np.nanmean(raes)) if raes else np.inf\n",
            "    return macro_rae, metrics, preds, ys, masks\n",
        ],
    },
    # --- CELL: Training loop ---
    {
        "cell_type": "code",
        "source": [
            "# === TRAINING LOOP ===\n",
            "\n",
            "optimizer = torch.optim.AdamW(model.parameters(), lr=BASE_LR, weight_decay=WEIGHT_DECAY)\n",
            "\n",
            "def lr_lambda(epoch):\n",
            "    if epoch < WARMUP_EPOCHS:\n",
            "        return (epoch + 1) / WARMUP_EPOCHS\n",
            "    progress = (epoch - WARMUP_EPOCHS) / max(1, T_MAX - WARMUP_EPOCHS)\n",
            "    cosine = 0.5 * (1 + math.cos(math.pi * progress))\n",
            "    return MIN_LR / BASE_LR + (1 - MIN_LR / BASE_LR) * cosine\n",
            "\n",
            "scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)\n",
            "\n",
            "# Tracking\n",
            "best_macro_rae = np.inf\n",
            "best_state = None\n",
            "best_epoch = 0\n",
            "history = []\n",
            "\n",
            "for epoch in range(1, EPOCHS + 1):\n",
            "    # --- Train ---\n",
            "    model.train()\n",
            "    train_losses = []\n",
            "    for batch in train_loader:\n",
            "        batch = batch.to(device)\n",
            "        optimizer.zero_grad()\n",
            "        out, _ = model(batch.x, batch.edge_index, batch.edge_attr,\n",
            "                       batch=batch.batch, zero_var=False)\n",
            "        T = out.size(1)\n",
            "        y = batch.y.view(-1, T)\n",
            "        mask = batch.y_mask.view(-1, T)\n",
            "        valid_mask = mask * (~torch.isnan(y)).float()\n",
            "        loss = custom_loss(out, y, valid_mask, task_scale=task_scale)\n",
            "        if torch.isnan(loss):\n",
            "            continue\n",
            "        loss.backward()\n",
            "        torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)\n",
            "        optimizer.step()\n",
            "        train_losses.append(loss.item())\n",
            "\n",
            "    lr_used = optimizer.param_groups[0]['lr']\n",
            "    scheduler.step()\n",
            "    avg_train_loss = np.mean(train_losses) if train_losses else np.nan\n",
            "\n",
            "    # --- Validate ---\n",
            "    val_rae, val_metrics, _, _, _ = evaluate_loader(model, val_loader, ENDPOINTS)\n",
            "\n",
            "    history.append({'epoch': epoch, 'train_loss': avg_train_loss, 'val_rae': val_rae, 'lr': lr_used})\n",
            "\n",
            "    # Best checkpoint by macro RAE\n",
            "    if val_rae < best_macro_rae:\n",
            "        best_macro_rae = val_rae\n",
            "        best_epoch = epoch\n",
            "        best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}\n",
            "\n",
            "    # Logging\n",
            "    if epoch == 1 or epoch % 25 == 0 or epoch == EPOCHS:\n",
            "        val_mae = np.nanmean([m.get('MAE', np.nan) for m in val_metrics.values()])\n",
            "        val_r2 = np.nanmean([m.get('R2', np.nan) for m in val_metrics.values()])\n",
            "        print(f'Epoch {epoch:4d}/{EPOCHS} | LR={lr_used:.1e} | '\n",
            "              f'train_loss={avg_train_loss:.4f} | val_RAE={val_rae:.4f} | '\n",
            "              f'val_MAE={val_mae:.4f} | val_R2={val_r2:.4f} | '\n",
            "              f'best_RAE={best_macro_rae:.4f}@{best_epoch}')\n",
            "\n",
            "print(f'\\nTraining complete. Best val macro RAE: {best_macro_rae:.4f} at epoch {best_epoch}')\n",
        ],
    },
    # --- CELL: Evaluation + predictions ---
    {
        "cell_type": "code",
        "source": [
            "# === EVALUATION + PREDICTIONS ===\n",
            "\n",
            "# Restore best model\n",
            "if best_state is not None:\n",
            "    model.load_state_dict(best_state)\n",
            "model = model.to(device)\n",
            "\n",
            "# Evaluate on all splits\n",
            "print('=== Validation set (best model) ===')\n",
            "val_rae, val_metrics, val_preds, val_ys, val_masks = evaluate_loader(model, val_loader, ENDPOINTS)\n",
            "for ep, m in val_metrics.items():\n",
            "    print(f'  {ep:25s}: MAE={m[\"MAE\"]:.4f}  RAE={m[\"RAE\"]:.4f}  R2={m[\"R2\"]:.4f}  rho={m[\"Spearman\"]:.4f}  tau={m[\"Kendall\"]:.4f}')\n",
            "print(f'  Macro RAE: {val_rae:.4f}')\n",
            "\n",
            "print('\\n=== Test set (from train split, best model) ===')\n",
            "test_rae, test_metrics, test_preds, test_ys, test_masks = evaluate_loader(model, test_from_train_loader, ENDPOINTS)\n",
            "for ep, m in test_metrics.items():\n",
            "    print(f'  {ep:25s}: MAE={m[\"MAE\"]:.4f}  RAE={m[\"RAE\"]:.4f}  R2={m[\"R2\"]:.4f}  rho={m[\"Spearman\"]:.4f}  tau={m[\"Kendall\"]:.4f}')\n",
            "print(f'  Macro RAE: {test_rae:.4f}')\n",
        ],
    },
    # --- CELL: External test predictions + clipping + inverse transform ---
    {
        "cell_type": "code",
        "source": [
            "# === EXTERNAL TEST PREDICTIONS ===\n",
            "\n",
            "# Compute training data range for clipping\n",
            "train_mins = {}\n",
            "train_maxs = {}\n",
            "for ep in ENDPOINTS:\n",
            "    vals = train_df[ep].dropna().values\n",
            "    train_mins[ep] = float(vals.min())\n",
            "    train_maxs[ep] = float(vals.max())\n",
            "\n",
            "# Predict on external test set\n",
            "ext_rae, ext_metrics, ext_preds, ext_ys, ext_masks = evaluate_loader(model, ext_test_loader, ENDPOINTS)\n",
            "\n",
            "# Clip predictions to train range ± DELTA\n",
            "for i, ep in enumerate(ENDPOINTS):\n",
            "    rng_ep = train_maxs[ep] - train_mins[ep]\n",
            "    lo = train_mins[ep] - DELTA * rng_ep\n",
            "    hi = train_maxs[ep] + DELTA * rng_ep\n",
            "    ext_preds[:, i] = np.clip(ext_preds[:, i], lo, hi)\n",
            "\n",
            "# Build predictions DataFrame (log scale)\n",
            "pred_df = pd.DataFrame()\n",
            "pred_df['SMILES'] = log_test_df['SMILES'].values\n",
            "pred_df['Molecule Name'] = log_test_df['Molecule Name'].values\n",
            "for i, ep in enumerate(ENDPOINTS):\n",
            "    pred_df[ep] = ext_preds[:, i]\n",
            "\n",
            "# Print external test metrics (log scale)\n",
            "print('=== External test metrics (log scale) ===')\n",
            "for ep, m in ext_metrics.items():\n",
            "    print(f'  {ep:25s}: MAE={m[\"MAE\"]:.4f}  RAE={m[\"RAE\"]:.4f}  R2={m[\"R2\"]:.4f}  rho={m[\"Spearman\"]:.4f}  tau={m[\"Kendall\"]:.4f}')\n",
            "print(f'  Macro RAE: {ext_rae:.4f}')\n",
            "\n",
            "# Save predictions\n",
            "output_dir = Path(f'../../experiments/{EXPERIMENT_NAME}')\n",
            "output_dir.mkdir(parents=True, exist_ok=True)\n",
            "pred_df.to_csv(output_dir / 'predictions_log_scale.csv', index=False)\n",
            "print(f'\\nPredictions saved to {output_dir / \"predictions_log_scale.csv\"}')\n",
        ],
    },
    # --- CELL: Summary ---
    {
        "cell_type": "code",
        "source": [
            "# === SUMMARY ===\n",
            "\n",
            "print(f'Experiment: {EXPERIMENT_NAME}')\n",
            "print(f'NUM_TASKS: {NUM_TASKS}')\n",
            "print(f'Pretrained: {PRETRAINED_CHECKPOINT is not None}')\n",
            "print(f'Best epoch: {best_epoch}')\n",
            "print(f'Best val macro RAE: {best_macro_rae:.4f}')\n",
            "print()\n",
            "\n",
            "# Summary table\n",
            "rows = []\n",
            "for ep in ENDPOINTS:\n",
            "    vm = val_metrics.get(ep, {})\n",
            "    em = ext_metrics.get(ep, {})\n",
            "    rows.append({\n",
            "        'Endpoint': ep,\n",
            "        'Val MAE': vm.get('MAE', np.nan),\n",
            "        'Val RAE': vm.get('RAE', np.nan),\n",
            "        'Val R2': vm.get('R2', np.nan),\n",
            "        'Ext MAE': em.get('MAE', np.nan),\n",
            "        'Ext RAE': em.get('RAE', np.nan),\n",
            "        'Ext R2': em.get('R2', np.nan),\n",
            "    })\n",
            "summary = pd.DataFrame(rows)\n",
            "print(summary.to_string(index=False, float_format='%.4f'))\n",
            "\n",
            "# Save training history\n",
            "hist_df = pd.DataFrame(history)\n",
            "hist_df.to_csv(output_dir / 'training_history.csv', index=False)\n",
            "print(f'\\nTraining history saved to {output_dir / \"training_history.csv\"}')\n",
        ],
    },
]


# ---------------------------------------------------------------------------
# Build notebooks
# ---------------------------------------------------------------------------

def make_cell(cell_type, source):
    """Create a Jupyter notebook cell dict."""
    cell = {
        "cell_type": cell_type,
        "metadata": {},
        "source": source,
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []
    return cell


def make_notebook(config_source, shared_cells):
    """Create a full notebook dict."""
    cells = [make_cell("code", config_source)]
    for sc in shared_cells:
        cells.append(make_cell(sc["cell_type"], sc["source"]))
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


if __name__ == "__main__":
    out_dir = Path(__file__).parent
    for variant in VARIANTS:
        nb = make_notebook(variant["config_source"], SHARED_CELLS)
        path = out_dir / variant["filename"]
        with open(path, "w") as f:
            json.dump(nb, f, indent=1)
        print(f"Written: {path}")
